apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "fabriq.fullname" . }}
  labels:
    {{- include "fabriq.labels" . | nindent 4 }}
data:
  FABRIQ_HTTP_ADDR: {{ .Values.config.httpAddr | quote }}
  {{- with .Values.config.reconcileInterval }}
  FABRIQ_RECONCILE_INTERVAL: {{ . | quote }}
  {{- end }}
  {{- range $k, $v := .Values.config.extraEnv }}
  {{ $k }}: {{ $v | quote }}
  {{- end }}
