{{- include "fabriq.validate" . -}}
{{- if not .Values.secret.existingSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "fabriq.fullname" . }}
  labels:
    {{- include "fabriq.labels" . | nindent 4 }}
type: Opaque
stringData:
  FABRIQ_POSTGRES_DSN: {{ .Values.secret.postgresDSN | quote }}
  {{- with .Values.secret.redisAddr }}
  FABRIQ_REDIS_ADDR: {{ . | quote }}
  {{- end }}
  {{- with .Values.secret.falkordbAddr }}
  FABRIQ_FALKORDB_ADDR: {{ . | quote }}
  {{- end }}
  {{- with .Values.secret.elasticsearchAddrs }}
  FABRIQ_ELASTICSEARCH_ADDRS: {{ . | quote }}
  {{- end }}
{{- end }}
