// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v7.35.0
// source: fabriq/v1/fabriq.proto

package fabriqpb

import (
	reflect "reflect"
	sync "sync"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Command mirrors core/command.Command. payload is the entity's grove model as
// OPAQUE bytes (canonical JSON today). The registry — not this schema — owns
// payload shape, so dynamic entities and map-native writes cross unchanged.
// op is "create" | "update" | "delete" | "upsert".
type Command struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Entity          string `protobuf:"bytes,1,opt,name=entity,proto3" json:"entity,omitempty"`
	Op              string `protobuf:"bytes,2,opt,name=op,proto3" json:"op,omitempty"`
	AggId           string `protobuf:"bytes,3,opt,name=agg_id,json=aggId,proto3" json:"agg_id,omitempty"`
	Payload         []byte `protobuf:"bytes,4,opt,name=payload,proto3" json:"payload,omitempty"`
	ExpectedVersion *int64 `protobuf:"varint,5,opt,name=expected_version,json=expectedVersion,proto3,oneof" json:"expected_version,omitempty"`
}

func (x *Command) Reset() {
	*x = Command{}
	if protoimpl.UnsafeEnabled {
		mi := &file_fabriq_v1_fabriq_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Command) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Command) ProtoMessage() {}

func (x *Command) ProtoReflect() protoreflect.Message {
	mi := &file_fabriq_v1_fabriq_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Command.ProtoReflect.Descriptor instead.
func (*Command) Descriptor() ([]byte, []int) {
	return file_fabriq_v1_fabriq_proto_rawDescGZIP(), []int{0}
}

func (x *Command) GetEntity() string {
	if x != nil {
		return x.Entity
	}
	return ""
}

func (x *Command) GetOp() string {
	if x != nil {
		return x.Op
	}
	return ""
}

func (x *Command) GetAggId() string {
	if x != nil {
		return x.AggId
	}
	return ""
}

func (x *Command) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Command) GetExpectedVersion() int64 {
	if x != nil && x.ExpectedVersion != nil {
		return *x.ExpectedVersion
	}
	return 0
}

type Result struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AggId   string `protobuf:"bytes,1,opt,name=agg_id,json=aggId,proto3" json:"agg_id,omitempty"`
	Version int64  `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	EventId string `protobuf:"bytes,3,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
}

func (x *Result) Reset() {
	*x = Result{}
	if protoimpl.UnsafeEnabled {
		mi := &file_fabriq_v1_fabriq_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Result) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Result) ProtoMessage() {}

func (x *Result) ProtoReflect() protoreflect.Message {
	mi := &file_fabriq_v1_fabriq_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Result.ProtoReflect.Descriptor instead.
func (*Result) Descriptor() ([]byte, []int) {
	return file_fabriq_v1_fabriq_proto_rawDescGZIP(), []int{1}
}

func (x *Result) GetAggId() string {
	if x != nil {
		return x.AggId
	}
	return ""
}

func (x *Result) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *Result) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

// Error carries fabriq's typed-error taxonomy so the client rebuilds
// errors.Is-matchable sentinels. code is stable: "not_found",
// "version_conflict", "no_tenant", "not_configured", "internal".
type Error struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code    string `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	AggId   string `protobuf:"bytes,3,opt,name=agg_id,json=aggId,proto3" json:"agg_id,omitempty"` // rich variants (version_conflict)
	Version int64  `protobuf:"varint,4,opt,name=version,proto3" json:"version,omitempty"`
}

func (x *Error) Reset() {
	*x = Error{}
	if protoimpl.UnsafeEnabled {
		mi := &file_fabriq_v1_fabriq_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Error) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Error) ProtoMessage() {}

func (x *Error) ProtoReflect() protoreflect.Message {
	mi := &file_fabriq_v1_fabriq_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Error.ProtoReflect.Descriptor instead.
func (*Error) Descriptor() ([]byte, []int) {
	return file_fabriq_v1_fabriq_proto_rawDescGZIP(), []int{2}
}

func (x *Error) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *Error) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Error) GetAggId() string {
	if x != nil {
		return x.AggId
	}
	return ""
}

func (x *Error) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

type ExecRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Command *Command `protobuf:"bytes,1,opt,name=command,proto3" json:"command,omitempty"`
}

func (x *ExecRequest) Reset() {
	*x = ExecRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_fabriq_v1_fabriq_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExecRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecRequest) ProtoMessage() {}

func (x *ExecRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fabriq_v1_fabriq_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecRequest.ProtoReflect.Descriptor instead.
func (*ExecRequest) Descriptor() ([]byte, []int) {
	return file_fabriq_v1_fabriq_proto_rawDescGZIP(), []int{3}
}

func (x *ExecRequest) GetCommand() *Command {
	if x != nil {
		return x.Command
	}
	return nil
}

type ExecReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result *Result `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	Error  *Error  `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *ExecReply) Reset() {
	*x = ExecReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_fabriq_v1_fabriq_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExecReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecReply) ProtoMessage() {}

func (x *ExecReply) ProtoReflect() protoreflect.Message {
	mi := &file_fabriq_v1_fabriq_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecReply.ProtoReflect.Descriptor instead.
func (*ExecReply) Descriptor() ([]byte, []int) {
	return file_fabriq_v1_fabriq_proto_rawDescGZIP(), []int{4}
}

func (x *ExecReply) GetResult() *Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *ExecReply) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

type ExecBatchRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Commands []*Command `protobuf:"bytes,1,rep,name=commands,proto3" json:"commands,omitempty"`
}

func (x *ExecBatchRequest) Reset() {
	*x = ExecBatchRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_fabriq_v1_fabriq_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExecBatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecBatchRequest) ProtoMessage() {}

func (x *ExecBatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fabriq_v1_fabriq_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecBatchRequest.ProtoReflect.Descriptor instead.
func (*ExecBatchRequest) Descriptor() ([]byte, []int) {
	return file_fabriq_v1_fabriq_proto_rawDescGZIP(), []int{5}
}

func (x *ExecBatchRequest) GetCommands() []*Command {
	if x != nil {
		return x.Commands
	}
	return nil
}

type ExecBatchReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Results []*Result `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	Error   *Error    `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *ExecBatchReply) Reset() {
	*x = ExecBatchReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_fabriq_v1_fabriq_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExecBatchReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecBatchReply) ProtoMessage() {}

func (x *ExecBatchReply) ProtoReflect() protoreflect.Message {
	mi := &file_fabriq_v1_fabriq_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecBatchReply.ProtoReflect.Descriptor instead.
func (*ExecBatchReply) Descriptor() ([]byte, []int) {
	return file_fabriq_v1_fabriq_proto_rawDescGZIP(), []int{6}
}

func (x *ExecBatchReply) GetResults() []*Result {
	if x != nil {
		return x.Results
	}
	return nil
}

func (x *ExecBatchReply) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

// --- reads (body is opaque JSON, like Command.payload) ---
type GetRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Entity string `protobuf:"bytes,1,opt,name=entity,proto3" json:"entity,omitempty"`
	Id     string `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetRequest) Reset() {
	*x = GetRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_fabriq_v1_fabriq_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRequest) ProtoMessage() {}

func (x *GetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fabriq_v1_fabriq_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRequest.ProtoReflect.Descriptor instead.
func (*GetRequest) Descriptor() ([]byte, []int) {
	return file_fabriq_v1_fabriq_proto_rawDescGZIP(), []int{7}
}

func (x *GetRequest) GetEntity() string {
	if x != nil {
		return x.Entity
	}
	return ""
}

func (x *GetRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetManyRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Entity string   `protobuf:"bytes,1,opt,name=entity,proto3" json:"entity,omitempty"`
	Ids    []string `protobuf:"bytes,2,rep,name=ids,proto3" json:"ids,omitempty"`
}

func (x *GetManyRequest) Reset() {
	*x = GetManyRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_fabriq_v1_fabriq_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetManyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetManyRequest) ProtoMessage() {}

func (x *GetManyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fabriq_v1_fabriq_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetManyRequest.ProtoReflect.Descriptor instead.
func (*GetManyRequest) Descriptor() ([]byte, []int) {
	return file_fabriq_v1_fabriq_proto_rawDescGZIP(), []int{8}
}

func (x *GetManyRequest) GetEntity() string {
	if x != nil {
		return x.Entity
	}
	return ""
}

func (x *GetManyRequest) GetIds() []string {
	if x != nil {
		return x.Ids
	}
	return nil
}

type ListRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Entity string `protobuf:"bytes,1,opt,name=entity,proto3" json:"entity,omitempty"`
	Query  []byte `protobuf:"bytes,2,opt,name=query,proto3" json:"query,omitempty"`
}

func (x *ListRequest) Reset() {
	*x = ListRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_fabriq_v1_fabriq_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRequest) ProtoMessage() {}

func (x *ListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fabriq_v1_fabriq_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRequest.ProtoReflect.Descriptor instead.
func (*ListRequest) Descriptor() ([]byte, []int) {
	return file_fabriq_v1_fabriq_proto_rawDescGZIP(), []int{9}
}

func (x *ListRequest) GetEntity() string {
	if x != nil {
		return x.Entity
	}
	return ""
}

func (x *ListRequest) GetQuery() []byte {
	if x != nil {
		return x.Query
	}
	return nil
}

type RowReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Row   []byte `protobuf:"bytes,1,opt,name=row,proto3" json:"row,omitempty"`
	Error *Error `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *RowReply) Reset() {
	*x = RowReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_fabriq_v1_fabriq_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RowReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RowReply) ProtoMessage() {}

func (x *RowReply) ProtoReflect() protoreflect.Message {
	mi := &file_fabriq_v1_fabriq_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RowReply.ProtoReflect.Descriptor instead.
func (*RowReply) Descriptor() ([]byte, []int) {
	return file_fabriq_v1_fabriq_proto_rawDescGZIP(), []int{10}
}

func (x *RowReply) GetRow() []byte {
	if x != nil {
		return x.Row
	}
	return nil
}

func (x *RowReply) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

// --- knowledge retrieval (vector / search / graph projection reads) ---
type Ack struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Error *Error `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *Ack) Reset() {
	*x = Ack{}
	if protoimpl.UnsafeEnabled {
		mi := &file_fabriq_v1_fabriq_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Ack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ack) ProtoMessage() {}

func (x *Ack) ProtoReflect() protoreflect.Message {
	mi := &file_fabriq_v1_fabriq_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ack.ProtoReflect.Descriptor instead.
func (*Ack) Descriptor() ([]byte, []int) {
	return file_fabriq_v1_fabriq_proto_rawDescGZIP(), []int{11}
}

func (x *Ack) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

type VectorSimilarRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Entity    string    `protobuf:"bytes,1,opt,name=entity,proto3" json:"entity,omitempty"`
	Embedding []float32 `protobuf:"fixed32,2,rep,packed,name=embedding,proto3" json:"embedding,omitempty"`
	K         int32     `protobuf:"varint,3,opt,name=k,proto3" json:"k,omitempty"`
}

func (x *VectorSimilarRequest) Reset() {
	*x = VectorSimilarRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_fabriq_v1_fabriq_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VectorSimilarRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VectorSimilarRequest) ProtoMessage() {}

func (x *VectorSimilarRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fabriq_v1_fabriq_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VectorSimilarRequest.ProtoReflect.Descriptor instead.
func (*VectorSimilarRequest) Descriptor() ([]byte, []int) {
	return file_fabriq_v1_fabriq_proto_rawDescGZIP(), []int{12}
}

func (x *VectorSimilarRequest) GetEntity() string {
	if x != nil {
		return x.Entity
	}
	return ""
}

func (x *VectorSimilarRequest) GetEmbedding() []float32 {
	if x != nil {
		return x.Embedding
	}
	return nil
}

func (x *VectorSimilarRequest) GetK() int32 {
	if x != nil {
		return x.K
	}
	return 0
}

type VectorUpsertRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Entity    string    `protobuf:"bytes,1,opt,name=entity,proto3" json:"entity,omitempty"`
	Id        string    `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Embedding []float32 `protobuf:"fixed32,3,rep,packed,name=embedding,proto3" json:"embedding,omitempty"`
	Meta      []byte    `protobuf:"bytes,4,opt,name=meta,proto3" json:"meta,omitempty"` // JSON map[string]any
}

func (x *VectorUpsertRequest) Reset() {
	*x = VectorUpsertRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_fabriq_v1_fabriq_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VectorUpsertRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VectorUpsertRequest) ProtoMessage() {}

func (x *VectorUpsertRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fabriq_v1_fabriq_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VectorUpsertRequest.ProtoReflect.Descriptor instead.
func (*VectorUpsertRequest) Descriptor() ([]byte, []int) {
	return file_fabriq_v1_fabriq_proto_rawDescGZIP(), []int{13}
}

func (x *VectorUpsertRequest) GetEntity() string {
	if x != nil {
		return x.Entity
	}
	return ""
}

func (x *VectorUpsertRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *VectorUpsertRequest) GetEmbedding() []float32 {
	if x != nil {
		return x.Embedding
	}
	return nil
}

func (x *VectorUpsertRequest) GetMeta() []byte {
	if x != nil {
		return x.Meta
	}
	return nil
}

type VectorDeleteRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Entity string `protobuf:"bytes,1,opt,name=entity,proto3" json:"entity,omitempty"`
	Id     string `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *VectorDeleteRequest) Reset() {
	*x = VectorDeleteRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_fabriq_v1_fabriq_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VectorDeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VectorDeleteRequest) ProtoMessage() {}

func (x *VectorDeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fabriq_v1_fabriq_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VectorDeleteRequest.ProtoReflect.Descriptor instead.
func (*VectorDeleteRequest) Descriptor() ([]byte, []int) {
	return file_fabriq_v1_fabriq_proto_rawDescGZIP(), []int{14}
}

func (x *VectorDeleteRequest) GetEntity() string {
	if x != nil {
		return x.Entity
	}
	return ""
}

func (x *VectorDeleteRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type SearchRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Query []byte `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
}

func (x *SearchRequest) Reset() {
	*x = SearchRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_fabriq_v1_fabriq_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchRequest) ProtoMessage() {}

func (x *SearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fabriq_v1_fabriq_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchRequest.ProtoReflect.Descriptor instead.
func (*SearchRequest) Descriptor() ([]byte, []int) {
	return file_fabriq_v1_fabriq_proto_rawDescGZIP(), []int{15}
}

func (x *SearchRequest) GetQuery() []byte {
	if x != nil {
		return x.Query
	}
	return nil
}

type GraphQueryRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Cypher string `protobuf:"bytes,1,opt,name=cypher,proto3" json:"cypher,omitempty"`
	Params []byte `protobuf:"bytes,2,opt,name=params,proto3" json:"params,omitempty"` // JSON map[string]any
	Mode   string `protobuf:"bytes,3,opt,name=mode,proto3" json:"mode,omitempty"`     // "ids" → []string, else → []map
}

func (x *GraphQueryRequest) Reset() {
	*x = GraphQueryRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_fabriq_v1_fabriq_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GraphQueryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GraphQueryRequest) ProtoMessage() {}

func (x *GraphQueryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fabriq_v1_fabriq_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GraphQueryRequest.ProtoReflect.Descriptor instead.
func (*GraphQueryRequest) Descriptor() ([]byte, []int) {
	return file_fabriq_v1_fabriq_proto_rawDescGZIP(), []int{16}
}

func (x *GraphQueryRequest) GetCypher() string {
	if x != nil {
		return x.Cypher
	}
	return ""
}

func (x *GraphQueryRequest) GetParams() []byte {
	if x != nil {
		return x.Params
	}
	return nil
}

func (x *GraphQueryRequest) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

// --- subscribe (conflated channel deltas) ---
type SubscribeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Scope *SubscribeScope `protobuf:"bytes,1,opt,name=scope,proto3" json:"scope,omitempty"`
}

func (x *SubscribeRequest) Reset() {
	*x = SubscribeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_fabriq_v1_fabriq_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SubscribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeRequest) ProtoMessage() {}

func (x *SubscribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fabriq_v1_fabriq_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeRequest.ProtoReflect.Descriptor instead.
func (*SubscribeRequest) Descriptor() ([]byte, []int) {
	return file_fabriq_v1_fabriq_proto_rawDescGZIP(), []int{17}
}

func (x *SubscribeRequest) GetScope() *SubscribeScope {
	if x != nil {
		return x.Scope
	}
	return nil
}

type SubscribeScope struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Entity string `protobuf:"bytes,1,opt,name=entity,proto3" json:"entity,omitempty"`
	Scope  string `protobuf:"bytes,2,opt,name=scope,proto3" json:"scope,omitempty"` // scope name declared on the entity ("id", "site", "tenant", …)
	Id     string `protobuf:"bytes,3,opt,name=id,proto3" json:"id,omitempty"`       // scope id (ignored for tenant scope)
}

func (x *SubscribeScope) Reset() {
	*x = SubscribeScope{}
	if protoimpl.UnsafeEnabled {
		mi := &file_fabriq_v1_fabriq_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SubscribeScope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeScope) ProtoMessage() {}

func (x *SubscribeScope) ProtoReflect() protoreflect.Message {
	mi := &file_fabriq_v1_fabriq_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeScope.ProtoReflect.Descriptor instead.
func (*SubscribeScope) Descriptor() ([]byte, []int) {
	return file_fabriq_v1_fabriq_proto_rawDescGZIP(), []int{18}
}

func (x *SubscribeScope) GetEntity() string {
	if x != nil {
		return x.Entity
	}
	return ""
}

func (x *SubscribeScope) GetScope() string {
	if x != nil {
		return x.Scope
	}
	return ""
}

func (x *SubscribeScope) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type Delta struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StreamId   string `protobuf:"bytes,1,opt,name=stream_id,json=streamId,proto3" json:"stream_id,omitempty"`
	Channel    string `protobuf:"bytes,2,opt,name=channel,proto3" json:"channel,omitempty"`
	TenantId   string `protobuf:"bytes,3,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Aggregate  string `protobuf:"bytes,4,opt,name=aggregate,proto3" json:"aggregate,omitempty"`
	AggId      string `protobuf:"bytes,5,opt,name=agg_id,json=aggId,proto3" json:"agg_id,omitempty"`
	Version    int64  `protobuf:"varint,6,opt,name=version,proto3" json:"version,omitempty"`
	Type       string `protobuf:"bytes,7,opt,name=type,proto3" json:"type,omitempty"`
	AtUnixNano int64  `protobuf:"varint,8,opt,name=at_unix_nano,json=atUnixNano,proto3" json:"at_unix_nano,omitempty"` // delivery timestamp, unix nanos
	Payload    []byte `protobuf:"bytes,9,opt,name=payload,proto3" json:"payload,omitempty"`                            // opaque JSON
}

func (x *Delta) Reset() {
	*x = Delta{}
	if protoimpl.UnsafeEnabled {
		mi := &file_fabriq_v1_fabriq_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Delta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Delta) ProtoMessage() {}

func (x *Delta) ProtoReflect() protoreflect.Message {
	mi := &file_fabriq_v1_fabriq_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Delta.ProtoReflect.Descriptor instead.
func (*Delta) Descriptor() ([]byte, []int) {
	return file_fabriq_v1_fabriq_proto_rawDescGZIP(), []int{19}
}

func (x *Delta) GetStreamId() string {
	if x != nil {
		return x.StreamId
	}
	return ""
}

func (x *Delta) GetChannel() string {
	if x != nil {
		return x.Channel
	}
	return ""
}

func (x *Delta) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *Delta) GetAggregate() string {
	if x != nil {
		return x.Aggregate
	}
	return ""
}

func (x *Delta) GetAggId() string {
	if x != nil {
		return x.AggId
	}
	return ""
}

func (x *Delta) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *Delta) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Delta) GetAtUnixNano() int64 {
	if x != nil {
		return x.AtUnixNano
	}
	return 0
}

func (x *Delta) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

// SubFrame is one frame of the Subscribe stream: the first is the handshake
// (open, or error on a setup failure such as authz); the rest carry one Delta.
type SubFrame struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Open  bool   `protobuf:"varint,1,opt,name=open,proto3" json:"open,omitempty"`
	Error *Error `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	Delta *Delta `protobuf:"bytes,3,opt,name=delta,proto3" json:"delta,omitempty"`
}

func (x *SubFrame) Reset() {
	*x = SubFrame{}
	if protoimpl.UnsafeEnabled {
		mi := &file_fabriq_v1_fabriq_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SubFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubFrame) ProtoMessage() {}

func (x *SubFrame) ProtoReflect() protoreflect.Message {
	mi := &file_fabriq_v1_fabriq_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubFrame.ProtoReflect.Descriptor instead.
func (*SubFrame) Descriptor() ([]byte, []int) {
	return file_fabriq_v1_fabriq_proto_rawDescGZIP(), []int{20}
}

func (x *SubFrame) GetOpen() bool {
	if x != nil {
		return x.Open
	}
	return false
}

func (x *SubFrame) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

func (x *SubFrame) GetDelta() *Delta {
	if x != nil {
		return x.Delta
	}
	return nil
}

// --- live query (maintained, ordered, filtered window) ---
type LiveQueryRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Query []byte `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
}

func (x *LiveQueryRequest) Reset() {
	*x = LiveQueryRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_fabriq_v1_fabriq_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LiveQueryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LiveQueryRequest) ProtoMessage() {}

func (x *LiveQueryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fabriq_v1_fabriq_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LiveQueryRequest.ProtoReflect.Descriptor instead.
func (*LiveQueryRequest) Descriptor() ([]byte, []int) {
	return file_fabriq_v1_fabriq_proto_rawDescGZIP(), []int{21}
}

func (x *LiveQueryRequest) GetQuery() []byte {
	if x != nil {
		return x.Query
	}
	return nil
}

// LiveFrame: the first frame carries the snapshot (or a setup error); each
// subsequent frame carries one delta. Bodies are opaque JSON.
type LiveFrame struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Snapshot []byte `protobuf:"bytes,1,opt,name=snapshot,proto3" json:"snapshot,omitempty"` // JSON livequery.Snapshot (first frame)
	Delta    []byte `protobuf:"bytes,2,opt,name=delta,proto3" json:"delta,omitempty"`       // JSON livequery.LiveDelta
	Error    *Error `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`       // setup error (handshake)
}

func (x *LiveFrame) Reset() {
	*x = LiveFrame{}
	if protoimpl.UnsafeEnabled {
		mi := &file_fabriq_v1_fabriq_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LiveFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LiveFrame) ProtoMessage() {}

func (x *LiveFrame) ProtoReflect() protoreflect.Message {
	mi := &file_fabriq_v1_fabriq_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LiveFrame.ProtoReflect.Descriptor instead.
func (*LiveFrame) Descriptor() ([]byte, []int) {
	return file_fabriq_v1_fabriq_proto_rawDescGZIP(), []int{22}
}

func (x *LiveFrame) GetSnapshot() []byte {
	if x != nil {
		return x.Snapshot
	}
	return nil
}

func (x *LiveFrame) GetDelta() []byte {
	if x != nil {
		return x.Delta
	}
	return nil
}

func (x *LiveFrame) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

// --- live (mirrors gateway/protocol.go) ---
type ClientCommand struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Action string `protobuf:"bytes,1,opt,name=action,proto3" json:"action,omitempty"` // "subscribe" | "reanchor" | "unsubscribe"
	Query  []byte `protobuf:"bytes,2,opt,name=query,proto3" json:"query,omitempty"`   // JSON LiveQuery (subscribe)
	Cursor []byte `protobuf:"bytes,3,opt,name=cursor,proto3" json:"cursor,omitempty"` // JSON Cursor (reanchor)
	Limit  int32  `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
}

func (x *ClientCommand) Reset() {
	*x = ClientCommand{}
	if protoimpl.UnsafeEnabled {
		mi := &file_fabriq_v1_fabriq_proto_msgTypes[23]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClientCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientCommand) ProtoMessage() {}

func (x *ClientCommand) ProtoReflect() protoreflect.Message {
	mi := &file_fabriq_v1_fabriq_proto_msgTypes[23]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientCommand.ProtoReflect.Descriptor instead.
func (*ClientCommand) Descriptor() ([]byte, []int) {
	return file_fabriq_v1_fabriq_proto_rawDescGZIP(), []int{23}
}

func (x *ClientCommand) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *ClientCommand) GetQuery() []byte {
	if x != nil {
		return x.Query
	}
	return nil
}

func (x *ClientCommand) GetCursor() []byte {
	if x != nil {
		return x.Cursor
	}
	return nil
}

func (x *ClientCommand) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type Frame struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Op       string `protobuf:"bytes,1,opt,name=op,proto3" json:"op,omitempty"` // "enter" | "leave" | "move" | "update" | "reset"
	AggId    string `protobuf:"bytes,2,opt,name=agg_id,json=aggId,proto3" json:"agg_id,omitempty"`
	Version  int64  `protobuf:"varint,3,opt,name=version,proto3" json:"version,omitempty"`
	Row      []byte `protobuf:"bytes,4,opt,name=row,proto3" json:"row,omitempty"`
	OldIndex int32  `protobuf:"varint,5,opt,name=old_index,json=oldIndex,proto3" json:"old_index,omitempty"`
	NewIndex int32  `protobuf:"varint,6,opt,name=new_index,json=newIndex,proto3" json:"new_index,omitempty"`
	Cursor   []byte `protobuf:"bytes,7,opt,name=cursor,proto3" json:"cursor,omitempty"`
	StreamId string `protobuf:"bytes,8,opt,name=stream_id,json=streamId,proto3" json:"stream_id,omitempty"`
}

func (x *Frame) Reset() {
	*x = Frame{}
	if protoimpl.UnsafeEnabled {
		mi := &file_fabriq_v1_fabriq_proto_msgTypes[24]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Frame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Frame) ProtoMessage() {}

func (x *Frame) ProtoReflect() protoreflect.Message {
	mi := &file_fabriq_v1_fabriq_proto_msgTypes[24]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Frame.ProtoReflect.Descriptor instead.
func (*Frame) Descriptor() ([]byte, []int) {
	return file_fabriq_v1_fabriq_proto_rawDescGZIP(), []int{24}
}

func (x *Frame) GetOp() string {
	if x != nil {
		return x.Op
	}
	return ""
}

func (x *Frame) GetAggId() string {
	if x != nil {
		return x.AggId
	}
	return ""
}

func (x *Frame) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *Frame) GetRow() []byte {
	if x != nil {
		return x.Row
	}
	return nil
}

func (x *Frame) GetOldIndex() int32 {
	if x != nil {
		return x.OldIndex
	}
	return 0
}

func (x *Frame) GetNewIndex() int32 {
	if x != nil {
		return x.NewIndex
	}
	return 0
}

func (x *Frame) GetCursor() []byte {
	if x != nil {
		return x.Cursor
	}
	return nil
}

func (x *Frame) GetStreamId() string {
	if x != nil {
		return x.StreamId
	}
	return ""
}

// --- blobs (core/blob.Store) ---
// PutBlob upload stream: the first frame carries metadata (key, content_type,
// size), each subsequent frame carries data bytes.
type BlobChunk struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key         string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	ContentType string `protobuf:"bytes,2,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	Size        int64  `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"` // declared size on the metadata frame, -1 if unknown
	Data        []byte `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`  // data frames
}

func (x *BlobChunk) Reset() {
	*x = BlobChunk{}
	if protoimpl.UnsafeEnabled {
		mi := &file_fabriq_v1_fabriq_proto_msgTypes[25]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BlobChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlobChunk) ProtoMessage() {}

func (x *BlobChunk) ProtoReflect() protoreflect.Message {
	mi := &file_fabriq_v1_fabriq_proto_msgTypes[25]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlobChunk.ProtoReflect.Descriptor instead.
func (*BlobChunk) Descriptor() ([]byte, []int) {
	return file_fabriq_v1_fabriq_proto_rawDescGZIP(), []int{25}
}

func (x *BlobChunk) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *BlobChunk) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *BlobChunk) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *BlobChunk) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type BlobKey struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
}

func (x *BlobKey) Reset() {
	*x = BlobKey{}
	if protoimpl.UnsafeEnabled {
		mi := &file_fabriq_v1_fabriq_proto_msgTypes[26]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BlobKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlobKey) ProtoMessage() {}

func (x *BlobKey) ProtoReflect() protoreflect.Message {
	mi := &file_fabriq_v1_fabriq_proto_msgTypes[26]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlobKey.ProtoReflect.Descriptor instead.
func (*BlobKey) Descriptor() ([]byte, []int) {
	return file_fabriq_v1_fabriq_proto_rawDescGZIP(), []int{26}
}

func (x *BlobKey) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type BlobObjectInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key                string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Size               int64  `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	Checksum           string `protobuf:"bytes,3,opt,name=checksum,proto3" json:"checksum,omitempty"`
	ContentType        string `protobuf:"bytes,4,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	ModifiedAtUnixNano int64  `protobuf:"varint,5,opt,name=modified_at_unix_nano,json=modifiedAtUnixNano,proto3" json:"modified_at_unix_nano,omitempty"`
}

func (x *BlobObjectInfo) Reset() {
	*x = BlobObjectInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_fabriq_v1_fabriq_proto_msgTypes[27]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BlobObjectInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlobObjectInfo) ProtoMessage() {}

func (x *BlobObjectInfo) ProtoReflect() protoreflect.Message {
	mi := &file_fabriq_v1_fabriq_proto_msgTypes[27]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlobObjectInfo.ProtoReflect.Descriptor instead.
func (*BlobObjectInfo) Descriptor() ([]byte, []int) {
	return file_fabriq_v1_fabriq_proto_rawDescGZIP(), []int{27}
}

func (x *BlobObjectInfo) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *BlobObjectInfo) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *BlobObjectInfo) GetChecksum() string {
	if x != nil {
		return x.Checksum
	}
	return ""
}

func (x *BlobObjectInfo) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *BlobObjectInfo) GetModifiedAtUnixNano() int64 {
	if x != nil {
		return x.ModifiedAtUnixNano
	}
	return 0
}

type BlobInfoReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Info  *BlobObjectInfo `protobuf:"bytes,1,opt,name=info,proto3" json:"info,omitempty"`
	Error *Error          `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *BlobInfoReply) Reset() {
	*x = BlobInfoReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_fabriq_v1_fabriq_proto_msgTypes[28]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BlobInfoReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlobInfoReply) ProtoMessage() {}

func (x *BlobInfoReply) ProtoReflect() protoreflect.Message {
	mi := &file_fabriq_v1_fabriq_proto_msgTypes[28]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlobInfoReply.ProtoReflect.Descriptor instead.
func (*BlobInfoReply) Descriptor() ([]byte, []int) {
	return file_fabriq_v1_fabriq_proto_rawDescGZIP(), []int{28}
}

func (x *BlobInfoReply) GetInfo() *BlobObjectInfo {
	if x != nil {
		return x.Info
	}
	return nil
}

func (x *BlobInfoReply) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

type BlobAck struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Error *Error `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *BlobAck) Reset() {
	*x = BlobAck{}
	if protoimpl.UnsafeEnabled {
		mi := &file_fabriq_v1_fabriq_proto_msgTypes[29]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BlobAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlobAck) ProtoMessage() {}

func (x *BlobAck) ProtoReflect() protoreflect.Message {
	mi := &file_fabriq_v1_fabriq_proto_msgTypes[29]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlobAck.ProtoReflect.Descriptor instead.
func (*BlobAck) Descriptor() ([]byte, []int) {
	return file_fabriq_v1_fabriq_proto_rawDescGZIP(), []int{29}
}

func (x *BlobAck) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

// GetBlob download stream: the first frame carries the object metadata (or a
// setup error such as not_found); each subsequent frame carries data bytes.
type GetBlobFrame struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Info  *BlobObjectInfo `protobuf:"bytes,1,opt,name=info,proto3" json:"info,omitempty"`
	Data  []byte          `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	Error *Error          `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *GetBlobFrame) Reset() {
	*x = GetBlobFrame{}
	if protoimpl.UnsafeEnabled {
		mi := &file_fabriq_v1_fabriq_proto_msgTypes[30]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetBlobFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBlobFrame) ProtoMessage() {}

func (x *GetBlobFrame) ProtoReflect() protoreflect.Message {
	mi := &file_fabriq_v1_fabriq_proto_msgTypes[30]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBlobFrame.ProtoReflect.Descriptor instead.
func (*GetBlobFrame) Descriptor() ([]byte, []int) {
	return file_fabriq_v1_fabriq_proto_rawDescGZIP(), []int{30}
}

func (x *GetBlobFrame) GetInfo() *BlobObjectInfo {
	if x != nil {
		return x.Info
	}
	return nil
}

func (x *GetBlobFrame) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *GetBlobFrame) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

type BlobPresign struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key        string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Method     string `protobuf:"bytes,2,opt,name=method,proto3" json:"method,omitempty"` // "GET" | "PUT"
	TtlSeconds int64  `protobuf:"varint,3,opt,name=ttl_seconds,json=ttlSeconds,proto3" json:"ttl_seconds,omitempty"`
}

func (x *BlobPresign) Reset() {
	*x = BlobPresign{}
	if protoimpl.UnsafeEnabled {
		mi := &file_fabriq_v1_fabriq_proto_msgTypes[31]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BlobPresign) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlobPresign) ProtoMessage() {}

func (x *BlobPresign) ProtoReflect() protoreflect.Message {
	mi := &file_fabriq_v1_fabriq_proto_msgTypes[31]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlobPresign.ProtoReflect.Descriptor instead.
func (*BlobPresign) Descriptor() ([]byte, []int) {
	return file_fabriq_v1_fabriq_proto_rawDescGZIP(), []int{31}
}

func (x *BlobPresign) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *BlobPresign) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *BlobPresign) GetTtlSeconds() int64 {
	if x != nil {
		return x.TtlSeconds
	}
	return 0
}

type BlobPresignReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Url   string `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	Error *Error `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *BlobPresignReply) Reset() {
	*x = BlobPresignReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_fabriq_v1_fabriq_proto_msgTypes[32]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BlobPresignReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlobPresignReply) ProtoMessage() {}

func (x *BlobPresignReply) ProtoReflect() protoreflect.Message {
	mi := &file_fabriq_v1_fabriq_proto_msgTypes[32]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlobPresignReply.ProtoReflect.Descriptor instead.
func (*BlobPresignReply) Descriptor() ([]byte, []int) {
	return file_fabriq_v1_fabriq_proto_rawDescGZIP(), []int{32}
}

func (x *BlobPresignReply) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *BlobPresignReply) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

var File_fabriq_v1_fabriq_proto protoreflect.FileDescriptor

var file_fabriq_v1_fabriq_proto_rawDesc = []byte{
	0x0a, 0x16, 0x66, 0x61, 0x62, 0x72, 0x69, 0x71, 0x2f, 0x76, 0x31, 0x2f, 0x66, 0x61, 0x62, 0x72,
	0x69, 0x71, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09, 0x66, 0x61, 0x62, 0x72, 0x69, 0x71,
	0x2e, 0x76, 0x31, 0x22, 0xa7, 0x01, 0x0a, 0x07, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x12,
	0x16, 0x0a, 0x06, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x12, 0x0e, 0x0a, 0x02, 0x6f, 0x70, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x02, 0x6f, 0x70, 0x12, 0x15, 0x0a, 0x06, 0x61, 0x67, 0x67, 0x5f, 0x69,
	0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x61, 0x67, 0x67, 0x49, 0x64, 0x12, 0x18,
	0x0a, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x12, 0x2e, 0x0a, 0x10, 0x65, 0x78, 0x70, 0x65,
	0x63, 0x74, 0x65, 0x64, 0x5f, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x03, 0x48, 0x00, 0x52, 0x0f, 0x65, 0x78, 0x70, 0x65, 0x63, 0x74, 0x65, 0x64, 0x56, 0x65,
	0x72, 0x73, 0x69, 0x6f, 0x6e, 0x88, 0x01, 0x01, 0x42, 0x13, 0x0a, 0x11, 0x5f, 0x65, 0x78, 0x70,
	0x65, 0x63, 0x74, 0x65, 0x64, 0x5f, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x22, 0x54, 0x0a,
	0x06, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x15, 0x0a, 0x06, 0x61, 0x67, 0x67, 0x5f, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x61, 0x67, 0x67, 0x49, 0x64, 0x12, 0x18,
	0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x19, 0x0a, 0x08, 0x65, 0x76, 0x65, 0x6e,
	0x74, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x65, 0x76, 0x65, 0x6e,
	0x74, 0x49, 0x64, 0x22, 0x66, 0x0a, 0x05, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x12, 0x0a, 0x04,
	0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65,
	0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x15, 0x0a, 0x06, 0x61, 0x67,
	0x67, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x61, 0x67, 0x67, 0x49,
	0x64, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x22, 0x3b, 0x0a, 0x0b, 0x45,
	0x78, 0x65, 0x63, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2c, 0x0a, 0x07, 0x63, 0x6f,
	0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x66, 0x61,
	0x62, 0x72, 0x69, 0x71, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x52,
	0x07, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x22, 0x5e, 0x0a, 0x09, 0x45, 0x78, 0x65, 0x63,
	0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x29, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x66, 0x61, 0x62, 0x72, 0x69, 0x71, 0x2e, 0x76,
	0x31, 0x2e, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74,
	0x12, 0x26, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x10, 0x2e, 0x66, 0x61, 0x62, 0x72, 0x69, 0x71, 0x2e, 0x76, 0x31, 0x2e, 0x45, 0x72, 0x72, 0x6f,
	0x72, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x22, 0x42, 0x0a, 0x10, 0x45, 0x78, 0x65, 0x63,
	0x42, 0x61, 0x74, 0x63, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2e, 0x0a, 0x08,
	0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x12,
	0x2e, 0x66, 0x61, 0x62, 0x72, 0x69, 0x71, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x61,
	0x6e, 0x64, 0x52, 0x08, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x73, 0x22, 0x65, 0x0a, 0x0e,
	0x45, 0x78, 0x65, 0x63, 0x42, 0x61, 0x74, 0x63, 0x68, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x2b,
	0x0a, 0x07, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x11, 0x2e, 0x66, 0x61, 0x62, 0x72, 0x69, 0x71, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x65, 0x73, 0x75,
	0x6c, 0x74, 0x52, 0x07, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x73, 0x12, 0x26, 0x0a, 0x05, 0x65,
	0x72, 0x72, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x66, 0x61, 0x62,
	0x72, 0x69, 0x71, 0x2e, 0x76, 0x31, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x52, 0x05, 0x65, 0x72,
	0x72, 0x6f, 0x72, 0x22, 0x34, 0x0a, 0x0a, 0x47, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x16, 0x0a, 0x06, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x3a, 0x0a, 0x0e, 0x47, 0x65, 0x74,
	0x4d, 0x61, 0x6e, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x65,
	0x6e, 0x74, 0x69, 0x74, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x65, 0x6e, 0x74,
	0x69, 0x74, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x69, 0x64, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09,
	0x52, 0x03, 0x69, 0x64, 0x73, 0x22, 0x3b, 0x0a, 0x0b, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x12, 0x14, 0x0a, 0x05,
	0x71, 0x75, 0x65, 0x72, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x71, 0x75, 0x65,
	0x72, 0x79, 0x22, 0x44, 0x0a, 0x08, 0x52, 0x6f, 0x77, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x10,
	0x0a, 0x03, 0x72, 0x6f, 0x77, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x03, 0x72, 0x6f, 0x77,
	0x12, 0x26, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x10, 0x2e, 0x66, 0x61, 0x62, 0x72, 0x69, 0x71, 0x2e, 0x76, 0x31, 0x2e, 0x45, 0x72, 0x72, 0x6f,
	0x72, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x22, 0x2d, 0x0a, 0x03, 0x41, 0x63, 0x6b, 0x12,
	0x26, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10,
	0x2e, 0x66, 0x61, 0x62, 0x72, 0x69, 0x71, 0x2e, 0x76, 0x31, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72,
	0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x22, 0x5a, 0x0a, 0x14, 0x56, 0x65, 0x63, 0x74, 0x6f,
	0x72, 0x53, 0x69, 0x6d, 0x69, 0x6c, 0x61, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x16, 0x0a, 0x06, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x12, 0x1c, 0x0a, 0x09, 0x65, 0x6d, 0x62, 0x65, 0x64,
	0x64, 0x69, 0x6e, 0x67, 0x18, 0x02, 0x20, 0x03, 0x28, 0x02, 0x52, 0x09, 0x65, 0x6d, 0x62, 0x65,
	0x64, 0x64, 0x69, 0x6e, 0x67, 0x12, 0x0c, 0x0a, 0x01, 0x6b, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x01, 0x6b, 0x22, 0x6f, 0x0a, 0x13, 0x56, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x55, 0x70, 0x73,
	0x65, 0x72, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x65, 0x6e,
	0x74, 0x69, 0x74, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x65, 0x6e, 0x74, 0x69,
	0x74, 0x79, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02,
	0x69, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x65, 0x6d, 0x62, 0x65, 0x64, 0x64, 0x69, 0x6e, 0x67, 0x18,
	0x03, 0x20, 0x03, 0x28, 0x02, 0x52, 0x09, 0x65, 0x6d, 0x62, 0x65, 0x64, 0x64, 0x69, 0x6e, 0x67,
	0x12, 0x12, 0x0a, 0x04, 0x6d, 0x65, 0x74, 0x61, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04,
	0x6d, 0x65, 0x74, 0x61, 0x22, 0x3d, 0x0a, 0x13, 0x56, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x44, 0x65,
	0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x65,
	0x6e, 0x74, 0x69, 0x74, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x65, 0x6e, 0x74,
	0x69, 0x74, 0x79, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x02, 0x69, 0x64, 0x22, 0x25, 0x0a, 0x0d, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x71, 0x75, 0x65, 0x72, 0x79, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x05, 0x71, 0x75, 0x65, 0x72, 0x79, 0x22, 0x57, 0x0a, 0x11, 0x47, 0x72,
	0x61, 0x70, 0x68, 0x51, 0x75, 0x65, 0x72, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x16, 0x0a, 0x06, 0x63, 0x79, 0x70, 0x68, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x63, 0x79, 0x70, 0x68, 0x65, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x70, 0x61, 0x72, 0x61, 0x6d,
	0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x06, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x12,
	0x12, 0x0a, 0x04, 0x6d, 0x6f, 0x64, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6d,
	0x6f, 0x64, 0x65, 0x22, 0x43, 0x0a, 0x10, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2f, 0x0a, 0x05, 0x73, 0x63, 0x6f, 0x70, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x66, 0x61, 0x62, 0x72, 0x69, 0x71, 0x2e,
	0x76, 0x31, 0x2e, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x53, 0x63, 0x6f, 0x70,
	0x65, 0x52, 0x05, 0x73, 0x63, 0x6f, 0x70, 0x65, 0x22, 0x4e, 0x0a, 0x0e, 0x53, 0x75, 0x62, 0x73,
	0x63, 0x72, 0x69, 0x62, 0x65, 0x53, 0x63, 0x6f, 0x70, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x65, 0x6e,
	0x74, 0x69, 0x74, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x65, 0x6e, 0x74, 0x69,
	0x74, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x63, 0x6f, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x73, 0x63, 0x6f, 0x70, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0xfa, 0x01, 0x0a, 0x05, 0x44, 0x65, 0x6c,
	0x74, 0x61, 0x12, 0x1b, 0x0a, 0x09, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x5f, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x49, 0x64, 0x12,
	0x18, 0x0a, 0x07, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x12, 0x1b, 0x0a, 0x09, 0x74, 0x65, 0x6e,
	0x61, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x74, 0x65,
	0x6e, 0x61, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x61, 0x67, 0x67, 0x72, 0x65, 0x67,
	0x61, 0x74, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x61, 0x67, 0x67, 0x72, 0x65,
	0x67, 0x61, 0x74, 0x65, 0x12, 0x15, 0x0a, 0x06, 0x61, 0x67, 0x67, 0x5f, 0x69, 0x64, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x61, 0x67, 0x67, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x76,
	0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x06, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x76, 0x65,
	0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x07, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x20, 0x0a, 0x0c, 0x61, 0x74, 0x5f,
	0x75, 0x6e, 0x69, 0x78, 0x5f, 0x6e, 0x61, 0x6e, 0x6f, 0x18, 0x08, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x0a, 0x61, 0x74, 0x55, 0x6e, 0x69, 0x78, 0x4e, 0x61, 0x6e, 0x6f, 0x12, 0x18, 0x0a, 0x07, 0x70,
	0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x18, 0x09, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x70, 0x61,
	0x79, 0x6c, 0x6f, 0x61, 0x64, 0x22, 0x6e, 0x0a, 0x08, 0x53, 0x75, 0x62, 0x46, 0x72, 0x61, 0x6d,
	0x65, 0x12, 0x12, 0x0a, 0x04, 0x6f, 0x70, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x04, 0x6f, 0x70, 0x65, 0x6e, 0x12, 0x26, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x66, 0x61, 0x62, 0x72, 0x69, 0x71, 0x2e, 0x76, 0x31,
	0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x26, 0x0a,
	0x05, 0x64, 0x65, 0x6c, 0x74, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x66,
	0x61, 0x62, 0x72, 0x69, 0x71, 0x2e, 0x76, 0x31, 0x2e, 0x44, 0x65, 0x6c, 0x74, 0x61, 0x52, 0x05,
	0x64, 0x65, 0x6c, 0x74, 0x61, 0x22, 0x28, 0x0a, 0x10, 0x4c, 0x69, 0x76, 0x65, 0x51, 0x75, 0x65,
	0x72, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x71, 0x75, 0x65,
	0x72, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x71, 0x75, 0x65, 0x72, 0x79, 0x22,
	0x65, 0x0a, 0x09, 0x4c, 0x69, 0x76, 0x65, 0x46, 0x72, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08,
	0x73, 0x6e, 0x61, 0x70, 0x73, 0x68, 0x6f, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x08,
	0x73, 0x6e, 0x61, 0x70, 0x73, 0x68, 0x6f, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x64, 0x65, 0x6c, 0x74,
	0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x64, 0x65, 0x6c, 0x74, 0x61, 0x12, 0x26,
	0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e,
	0x66, 0x61, 0x62, 0x72, 0x69, 0x71, 0x2e, 0x76, 0x31, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x52,
	0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x22, 0x6b, 0x0a, 0x0d, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74,
	0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12,
	0x14, 0x0a, 0x05, 0x71, 0x75, 0x65, 0x72, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05,
	0x71, 0x75, 0x65, 0x72, 0x79, 0x12, 0x16, 0x0a, 0x06, 0x63, 0x75, 0x72, 0x73, 0x6f, 0x72, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x06, 0x63, 0x75, 0x72, 0x73, 0x6f, 0x72, 0x12, 0x14, 0x0a,
	0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x6c, 0x69,
	0x6d, 0x69, 0x74, 0x22, 0xc9, 0x01, 0x0a, 0x05, 0x46, 0x72, 0x61, 0x6d, 0x65, 0x12, 0x0e, 0x0a,
	0x02, 0x6f, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x6f, 0x70, 0x12, 0x15, 0x0a,
	0x06, 0x61, 0x67, 0x67, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x61,
	0x67, 0x67, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x10,
	0x0a, 0x03, 0x72, 0x6f, 0x77, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x03, 0x72, 0x6f, 0x77,
	0x12, 0x1b, 0x0a, 0x09, 0x6f, 0x6c, 0x64, 0x5f, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x08, 0x6f, 0x6c, 0x64, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x12, 0x1b, 0x0a,
	0x09, 0x6e, 0x65, 0x77, 0x5f, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x06, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x08, 0x6e, 0x65, 0x77, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x12, 0x16, 0x0a, 0x06, 0x63, 0x75,
	0x72, 0x73, 0x6f, 0x72, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x06, 0x63, 0x75, 0x72, 0x73,
	0x6f, 0x72, 0x12, 0x1b, 0x0a, 0x09, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x5f, 0x69, 0x64, 0x18,
	0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x49, 0x64, 0x22,
	0x68, 0x0a, 0x09, 0x42, 0x6c, 0x6f, 0x62, 0x43, 0x68, 0x75, 0x6e, 0x6b, 0x12, 0x10, 0x0a, 0x03,
	0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x21,
	0x0a, 0x0c, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70,
	0x65, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x04, 0x73, 0x69, 0x7a, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x1b, 0x0a, 0x07, 0x42, 0x6c, 0x6f,
	0x62, 0x4b, 0x65, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x22, 0xa8, 0x01, 0x0a, 0x0e, 0x42, 0x6c, 0x6f, 0x62, 0x4f,
	0x62, 0x6a, 0x65, 0x63, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x73,
	0x69, 0x7a, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x12,
	0x1a, 0x0a, 0x08, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x73, 0x75, 0x6d, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x73, 0x75, 0x6d, 0x12, 0x21, 0x0a, 0x0c, 0x63,
	0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0b, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x31,
	0x0a, 0x15, 0x6d, 0x6f, 0x64, 0x69, 0x66, 0x69, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x5f, 0x75, 0x6e,
	0x69, 0x78, 0x5f, 0x6e, 0x61, 0x6e, 0x6f, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x12, 0x6d,
	0x6f, 0x64, 0x69, 0x66, 0x69, 0x65, 0x64, 0x41, 0x74, 0x55, 0x6e, 0x69, 0x78, 0x4e, 0x61, 0x6e,
	0x6f, 0x22, 0x66, 0x0a, 0x0d, 0x42, 0x6c, 0x6f, 0x62, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x70,
	0x6c, 0x79, 0x12, 0x2d, 0x0a, 0x04, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x19, 0x2e, 0x66, 0x61, 0x62, 0x72, 0x69, 0x71, 0x2e, 0x76, 0x31, 0x2e, 0x42, 0x6c, 0x6f,
	0x62, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x04, 0x69, 0x6e, 0x66,
	0x6f, 0x12, 0x26, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x10, 0x2e, 0x66, 0x61, 0x62, 0x72, 0x69, 0x71, 0x2e, 0x76, 0x31, 0x2e, 0x45, 0x72, 0x72,
	0x6f, 0x72, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x22, 0x31, 0x0a, 0x07, 0x42, 0x6c, 0x6f,
	0x62, 0x41, 0x63, 0x6b, 0x12, 0x26, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x66, 0x61, 0x62, 0x72, 0x69, 0x71, 0x2e, 0x76, 0x31, 0x2e,
	0x45, 0x72, 0x72, 0x6f, 0x72, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x22, 0x79, 0x0a, 0x0c,
	0x47, 0x65, 0x74, 0x42, 0x6c, 0x6f, 0x62, 0x46, 0x72, 0x61, 0x6d, 0x65, 0x12, 0x2d, 0x0a, 0x04,
	0x69, 0x6e, 0x66, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x66, 0x61, 0x62,
	0x72, 0x69, 0x71, 0x2e, 0x76, 0x31, 0x2e, 0x42, 0x6c, 0x6f, 0x62, 0x4f, 0x62, 0x6a, 0x65, 0x63,
	0x74, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x04, 0x69, 0x6e, 0x66, 0x6f, 0x12, 0x12, 0x0a, 0x04, 0x64,
	0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x12,
	0x26, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10,
	0x2e, 0x66, 0x61, 0x62, 0x72, 0x69, 0x71, 0x2e, 0x76, 0x31, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72,
	0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x22, 0x58, 0x0a, 0x0b, 0x42, 0x6c, 0x6f, 0x62, 0x50,
	0x72, 0x65, 0x73, 0x69, 0x67, 0x6e, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x16, 0x0a, 0x06, 0x6d, 0x65, 0x74, 0x68,
	0x6f, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64,
	0x12, 0x1f, 0x0a, 0x0b, 0x74, 0x74, 0x6c, 0x5f, 0x73, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x73, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x74, 0x74, 0x6c, 0x53, 0x65, 0x63, 0x6f, 0x6e, 0x64,
	0x73, 0x22, 0x4c, 0x0a, 0x10, 0x42, 0x6c, 0x6f, 0x62, 0x50, 0x72, 0x65, 0x73, 0x69, 0x67, 0x6e,
	0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x72, 0x6c, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x03, 0x75, 0x72, 0x6c, 0x12, 0x26, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x66, 0x61, 0x62, 0x72, 0x69, 0x71, 0x2e,
	0x76, 0x31, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x32,
	0xd1, 0x08, 0x0a, 0x06, 0x46, 0x61, 0x62, 0x72, 0x69, 0x71, 0x12, 0x34, 0x0a, 0x04, 0x45, 0x78,
	0x65, 0x63, 0x12, 0x16, 0x2e, 0x66, 0x61, 0x62, 0x72, 0x69, 0x71, 0x2e, 0x76, 0x31, 0x2e, 0x45,
	0x78, 0x65, 0x63, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x14, 0x2e, 0x66, 0x61, 0x62,
	0x72, 0x69, 0x71, 0x2e, 0x76, 0x31, 0x2e, 0x45, 0x78, 0x65, 0x63, 0x52, 0x65, 0x70, 0x6c, 0x79,
	0x12, 0x43, 0x0a, 0x09, 0x45, 0x78, 0x65, 0x63, 0x42, 0x61, 0x74, 0x63, 0x68, 0x12, 0x1b, 0x2e,
	0x66, 0x61, 0x62, 0x72, 0x69, 0x71, 0x2e, 0x76, 0x31, 0x2e, 0x45, 0x78, 0x65, 0x63, 0x42, 0x61,
	0x74, 0x63, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x66, 0x61, 0x62,
	0x72, 0x69, 0x71, 0x2e, 0x76, 0x31, 0x2e, 0x45, 0x78, 0x65, 0x63, 0x42, 0x61, 0x74, 0x63, 0x68,
	0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x31, 0x0a, 0x03, 0x47, 0x65, 0x74, 0x12, 0x15, 0x2e, 0x66,
	0x61, 0x62, 0x72, 0x69, 0x71, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x13, 0x2e, 0x66, 0x61, 0x62, 0x72, 0x69, 0x71, 0x2e, 0x76, 0x31, 0x2e,
	0x52, 0x6f, 0x77, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x35, 0x0a, 0x04, 0x4c, 0x69, 0x73, 0x74,
	0x12, 0x16, 0x2e, 0x66, 0x61, 0x62, 0x72, 0x69, 0x71, 0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x69, 0x73,
	0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x13, 0x2e, 0x66, 0x61, 0x62, 0x72, 0x69,
	0x71, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x6f, 0x77, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x30, 0x01, 0x12,
	0x3b, 0x0a, 0x07, 0x47, 0x65, 0x74, 0x4d, 0x61, 0x6e, 0x79, 0x12, 0x19, 0x2e, 0x66, 0x61, 0x62,
	0x72, 0x69, 0x71, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x4d, 0x61, 0x6e, 0x79, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x13, 0x2e, 0x66, 0x61, 0x62, 0x72, 0x69, 0x71, 0x2e, 0x76,
	0x31, 0x2e, 0x52, 0x6f, 0x77, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x30, 0x01, 0x12, 0x45, 0x0a, 0x0d,
	0x56, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x53, 0x69, 0x6d, 0x69, 0x6c, 0x61, 0x72, 0x12, 0x1f, 0x2e,
	0x66, 0x61, 0x62, 0x72, 0x69, 0x71, 0x2e, 0x76, 0x31, 0x2e, 0x56, 0x65, 0x63, 0x74, 0x6f, 0x72,
	0x53, 0x69, 0x6d, 0x69, 0x6c, 0x61, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x13,
	0x2e, 0x66, 0x61, 0x62, 0x72, 0x69, 0x71, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x6f, 0x77, 0x52, 0x65,
	0x70, 0x6c, 0x79, 0x12, 0x3e, 0x0a, 0x0c, 0x56, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x55, 0x70, 0x73,
	0x65, 0x72, 0x74, 0x12, 0x1e, 0x2e, 0x66, 0x61, 0x62, 0x72, 0x69, 0x71, 0x2e, 0x76, 0x31, 0x2e,
	0x56, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x55, 0x70, 0x73, 0x65, 0x72, 0x74, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x0e, 0x2e, 0x66, 0x61, 0x62, 0x72, 0x69, 0x71, 0x2e, 0x76, 0x31, 0x2e,
	0x41, 0x63, 0x6b, 0x12, 0x3e, 0x0a, 0x0c, 0x56, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x44, 0x65, 0x6c,
	0x65, 0x74, 0x65, 0x12, 0x1e, 0x2e, 0x66, 0x61, 0x62, 0x72, 0x69, 0x71, 0x2e, 0x76, 0x31, 0x2e,
	0x56, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x0e, 0x2e, 0x66, 0x61, 0x62, 0x72, 0x69, 0x71, 0x2e, 0x76, 0x31, 0x2e,
	0x41, 0x63, 0x6b, 0x12, 0x37, 0x0a, 0x06, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x12, 0x18, 0x2e,
	0x66, 0x61, 0x62, 0x72, 0x69, 0x71, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x13, 0x2e, 0x66, 0x61, 0x62, 0x72, 0x69, 0x71,
	0x2e, 0x76, 0x31, 0x2e, 0x52, 0x6f, 0x77, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x3f, 0x0a, 0x0a,
	0x47, 0x72, 0x61, 0x70, 0x68, 0x51, 0x75, 0x65, 0x72, 0x79, 0x12, 0x1c, 0x2e, 0x66, 0x61, 0x62,
	0x72, 0x69, 0x71, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x72, 0x61, 0x70, 0x68, 0x51, 0x75, 0x65, 0x72,
	0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x13, 0x2e, 0x66, 0x61, 0x62, 0x72, 0x69,
	0x71, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x6f, 0x77, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x3f, 0x0a,
	0x09, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x12, 0x1b, 0x2e, 0x66, 0x61, 0x62,
	0x72, 0x69, 0x71, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x13, 0x2e, 0x66, 0x61, 0x62, 0x72, 0x69, 0x71,
	0x2e, 0x76, 0x31, 0x2e, 0x53, 0x75, 0x62, 0x46, 0x72, 0x61, 0x6d, 0x65, 0x30, 0x01, 0x12, 0x40,
	0x0a, 0x09, 0x4c, 0x69, 0x76, 0x65, 0x51, 0x75, 0x65, 0x72, 0x79, 0x12, 0x1b, 0x2e, 0x66, 0x61,
	0x62, 0x72, 0x69, 0x71, 0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x69, 0x76, 0x65, 0x51, 0x75, 0x65, 0x72,
	0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x14, 0x2e, 0x66, 0x61, 0x62, 0x72, 0x69,
	0x71, 0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x69, 0x76, 0x65, 0x46, 0x72, 0x61, 0x6d, 0x65, 0x30, 0x01,
	0x12, 0x36, 0x0a, 0x04, 0x4c, 0x69, 0x76, 0x65, 0x12, 0x18, 0x2e, 0x66, 0x61, 0x62, 0x72, 0x69,
	0x71, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x43, 0x6f, 0x6d, 0x6d, 0x61,
	0x6e, 0x64, 0x1a, 0x10, 0x2e, 0x66, 0x61, 0x62, 0x72, 0x69, 0x71, 0x2e, 0x76, 0x31, 0x2e, 0x46,
	0x72, 0x61, 0x6d, 0x65, 0x28, 0x01, 0x30, 0x01, 0x12, 0x3b, 0x0a, 0x07, 0x50, 0x75, 0x74, 0x42,
	0x6c, 0x6f, 0x62, 0x12, 0x14, 0x2e, 0x66, 0x61, 0x62, 0x72, 0x69, 0x71, 0x2e, 0x76, 0x31, 0x2e,
	0x42, 0x6c, 0x6f, 0x62, 0x43, 0x68, 0x75, 0x6e, 0x6b, 0x1a, 0x18, 0x2e, 0x66, 0x61, 0x62, 0x72,
	0x69, 0x71, 0x2e, 0x76, 0x31, 0x2e, 0x42, 0x6c, 0x6f, 0x62, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65,
	0x70, 0x6c, 0x79, 0x28, 0x01, 0x12, 0x38, 0x0a, 0x07, 0x47, 0x65, 0x74, 0x42, 0x6c, 0x6f, 0x62,
	0x12, 0x12, 0x2e, 0x66, 0x61, 0x62, 0x72, 0x69, 0x71, 0x2e, 0x76, 0x31, 0x2e, 0x42, 0x6c, 0x6f,
	0x62, 0x4b, 0x65, 0x79, 0x1a, 0x17, 0x2e, 0x66, 0x61, 0x62, 0x72, 0x69, 0x71, 0x2e, 0x76, 0x31,
	0x2e, 0x47, 0x65, 0x74, 0x42, 0x6c, 0x6f, 0x62, 0x46, 0x72, 0x61, 0x6d, 0x65, 0x30, 0x01, 0x12,
	0x38, 0x0a, 0x08, 0x48, 0x65, 0x61, 0x64, 0x42, 0x6c, 0x6f, 0x62, 0x12, 0x12, 0x2e, 0x66, 0x61,
	0x62, 0x72, 0x69, 0x71, 0x2e, 0x76, 0x31, 0x2e, 0x42, 0x6c, 0x6f, 0x62, 0x4b, 0x65, 0x79, 0x1a,
	0x18, 0x2e, 0x66, 0x61, 0x62, 0x72, 0x69, 0x71, 0x2e, 0x76, 0x31, 0x2e, 0x42, 0x6c, 0x6f, 0x62,
	0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x34, 0x0a, 0x0a, 0x44, 0x65, 0x6c,
	0x65, 0x74, 0x65, 0x42, 0x6c, 0x6f, 0x62, 0x12, 0x12, 0x2e, 0x66, 0x61, 0x62, 0x72, 0x69, 0x71,
	0x2e, 0x76, 0x31, 0x2e, 0x42, 0x6c, 0x6f, 0x62, 0x4b, 0x65, 0x79, 0x1a, 0x12, 0x2e, 0x66, 0x61,
	0x62, 0x72, 0x69, 0x71, 0x2e, 0x76, 0x31, 0x2e, 0x42, 0x6c, 0x6f, 0x62, 0x41, 0x63, 0x6b, 0x12,
	0x42, 0x0a, 0x0b, 0x50, 0x72, 0x65, 0x73, 0x69, 0x67, 0x6e, 0x42, 0x6c, 0x6f, 0x62, 0x12, 0x16,
	0x2e, 0x66, 0x61, 0x62, 0x72, 0x69, 0x71, 0x2e, 0x76, 0x31, 0x2e, 0x42, 0x6c, 0x6f, 0x62, 0x50,
	0x72, 0x65, 0x73, 0x69, 0x67, 0x6e, 0x1a, 0x1b, 0x2e, 0x66, 0x61, 0x62, 0x72, 0x69, 0x71, 0x2e,
	0x76, 0x31, 0x2e, 0x42, 0x6c, 0x6f, 0x62, 0x50, 0x72, 0x65, 0x73, 0x69, 0x67, 0x6e, 0x52, 0x65,
	0x70, 0x6c, 0x79, 0x42, 0x32, 0x5a, 0x30, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f,
	0x6d, 0x2f, 0x78, 0x72, 0x61, 0x70, 0x68, 0x2f, 0x66, 0x61, 0x62, 0x72, 0x69, 0x71, 0x2f, 0x72,
	0x65, 0x6d, 0x6f, 0x74, 0x65, 0x2f, 0x66, 0x61, 0x62, 0x72, 0x69, 0x71, 0x70, 0x62, 0x3b, 0x66,
	0x61, 0x62, 0x72, 0x69, 0x71, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_fabriq_v1_fabriq_proto_rawDescOnce sync.Once
	file_fabriq_v1_fabriq_proto_rawDescData = file_fabriq_v1_fabriq_proto_rawDesc
)

func file_fabriq_v1_fabriq_proto_rawDescGZIP() []byte {
	file_fabriq_v1_fabriq_proto_rawDescOnce.Do(func() {
		file_fabriq_v1_fabriq_proto_rawDescData = protoimpl.X.CompressGZIP(file_fabriq_v1_fabriq_proto_rawDescData)
	})
	return file_fabriq_v1_fabriq_proto_rawDescData
}

var file_fabriq_v1_fabriq_proto_msgTypes = make([]protoimpl.MessageInfo, 33)
var file_fabriq_v1_fabriq_proto_goTypes = []any{
	(*Command)(nil),              // 0: fabriq.v1.Command
	(*Result)(nil),               // 1: fabriq.v1.Result
	(*Error)(nil),                // 2: fabriq.v1.Error
	(*ExecRequest)(nil),          // 3: fabriq.v1.ExecRequest
	(*ExecReply)(nil),            // 4: fabriq.v1.ExecReply
	(*ExecBatchRequest)(nil),     // 5: fabriq.v1.ExecBatchRequest
	(*ExecBatchReply)(nil),       // 6: fabriq.v1.ExecBatchReply
	(*GetRequest)(nil),           // 7: fabriq.v1.GetRequest
	(*GetManyRequest)(nil),       // 8: fabriq.v1.GetManyRequest
	(*ListRequest)(nil),          // 9: fabriq.v1.ListRequest
	(*RowReply)(nil),             // 10: fabriq.v1.RowReply
	(*Ack)(nil),                  // 11: fabriq.v1.Ack
	(*VectorSimilarRequest)(nil), // 12: fabriq.v1.VectorSimilarRequest
	(*VectorUpsertRequest)(nil),  // 13: fabriq.v1.VectorUpsertRequest
	(*VectorDeleteRequest)(nil),  // 14: fabriq.v1.VectorDeleteRequest
	(*SearchRequest)(nil),        // 15: fabriq.v1.SearchRequest
	(*GraphQueryRequest)(nil),    // 16: fabriq.v1.GraphQueryRequest
	(*SubscribeRequest)(nil),     // 17: fabriq.v1.SubscribeRequest
	(*SubscribeScope)(nil),       // 18: fabriq.v1.SubscribeScope
	(*Delta)(nil),                // 19: fabriq.v1.Delta
	(*SubFrame)(nil),             // 20: fabriq.v1.SubFrame
	(*LiveQueryRequest)(nil),     // 21: fabriq.v1.LiveQueryRequest
	(*LiveFrame)(nil),            // 22: fabriq.v1.LiveFrame
	(*ClientCommand)(nil),        // 23: fabriq.v1.ClientCommand
	(*Frame)(nil),                // 24: fabriq.v1.Frame
	(*BlobChunk)(nil),            // 25: fabriq.v1.BlobChunk
	(*BlobKey)(nil),              // 26: fabriq.v1.BlobKey
	(*BlobObjectInfo)(nil),       // 27: fabriq.v1.BlobObjectInfo
	(*BlobInfoReply)(nil),        // 28: fabriq.v1.BlobInfoReply
	(*BlobAck)(nil),              // 29: fabriq.v1.BlobAck
	(*GetBlobFrame)(nil),         // 30: fabriq.v1.GetBlobFrame
	(*BlobPresign)(nil),          // 31: fabriq.v1.BlobPresign
	(*BlobPresignReply)(nil),     // 32: fabriq.v1.BlobPresignReply
}
var file_fabriq_v1_fabriq_proto_depIdxs = []int32{
	0,  // 0: fabriq.v1.ExecRequest.command:type_name -> fabriq.v1.Command
	1,  // 1: fabriq.v1.ExecReply.result:type_name -> fabriq.v1.Result
	2,  // 2: fabriq.v1.ExecReply.error:type_name -> fabriq.v1.Error
	0,  // 3: fabriq.v1.ExecBatchRequest.commands:type_name -> fabriq.v1.Command
	1,  // 4: fabriq.v1.ExecBatchReply.results:type_name -> fabriq.v1.Result
	2,  // 5: fabriq.v1.ExecBatchReply.error:type_name -> fabriq.v1.Error
	2,  // 6: fabriq.v1.RowReply.error:type_name -> fabriq.v1.Error
	2,  // 7: fabriq.v1.Ack.error:type_name -> fabriq.v1.Error
	18, // 8: fabriq.v1.SubscribeRequest.scope:type_name -> fabriq.v1.SubscribeScope
	2,  // 9: fabriq.v1.SubFrame.error:type_name -> fabriq.v1.Error
	19, // 10: fabriq.v1.SubFrame.delta:type_name -> fabriq.v1.Delta
	2,  // 11: fabriq.v1.LiveFrame.error:type_name -> fabriq.v1.Error
	27, // 12: fabriq.v1.BlobInfoReply.info:type_name -> fabriq.v1.BlobObjectInfo
	2,  // 13: fabriq.v1.BlobInfoReply.error:type_name -> fabriq.v1.Error
	2,  // 14: fabriq.v1.BlobAck.error:type_name -> fabriq.v1.Error
	27, // 15: fabriq.v1.GetBlobFrame.info:type_name -> fabriq.v1.BlobObjectInfo
	2,  // 16: fabriq.v1.GetBlobFrame.error:type_name -> fabriq.v1.Error
	2,  // 17: fabriq.v1.BlobPresignReply.error:type_name -> fabriq.v1.Error
	3,  // 18: fabriq.v1.Fabriq.Exec:input_type -> fabriq.v1.ExecRequest
	5,  // 19: fabriq.v1.Fabriq.ExecBatch:input_type -> fabriq.v1.ExecBatchRequest
	7,  // 20: fabriq.v1.Fabriq.Get:input_type -> fabriq.v1.GetRequest
	9,  // 21: fabriq.v1.Fabriq.List:input_type -> fabriq.v1.ListRequest
	8,  // 22: fabriq.v1.Fabriq.GetMany:input_type -> fabriq.v1.GetManyRequest
	12, // 23: fabriq.v1.Fabriq.VectorSimilar:input_type -> fabriq.v1.VectorSimilarRequest
	13, // 24: fabriq.v1.Fabriq.VectorUpsert:input_type -> fabriq.v1.VectorUpsertRequest
	14, // 25: fabriq.v1.Fabriq.VectorDelete:input_type -> fabriq.v1.VectorDeleteRequest
	15, // 26: fabriq.v1.Fabriq.Search:input_type -> fabriq.v1.SearchRequest
	16, // 27: fabriq.v1.Fabriq.GraphQuery:input_type -> fabriq.v1.GraphQueryRequest
	17, // 28: fabriq.v1.Fabriq.Subscribe:input_type -> fabriq.v1.SubscribeRequest
	21, // 29: fabriq.v1.Fabriq.LiveQuery:input_type -> fabriq.v1.LiveQueryRequest
	23, // 30: fabriq.v1.Fabriq.Live:input_type -> fabriq.v1.ClientCommand
	25, // 31: fabriq.v1.Fabriq.PutBlob:input_type -> fabriq.v1.BlobChunk
	26, // 32: fabriq.v1.Fabriq.GetBlob:input_type -> fabriq.v1.BlobKey
	26, // 33: fabriq.v1.Fabriq.HeadBlob:input_type -> fabriq.v1.BlobKey
	26, // 34: fabriq.v1.Fabriq.DeleteBlob:input_type -> fabriq.v1.BlobKey
	31, // 35: fabriq.v1.Fabriq.PresignBlob:input_type -> fabriq.v1.BlobPresign
	4,  // 36: fabriq.v1.Fabriq.Exec:output_type -> fabriq.v1.ExecReply
	6,  // 37: fabriq.v1.Fabriq.ExecBatch:output_type -> fabriq.v1.ExecBatchReply
	10, // 38: fabriq.v1.Fabriq.Get:output_type -> fabriq.v1.RowReply
	10, // 39: fabriq.v1.Fabriq.List:output_type -> fabriq.v1.RowReply
	10, // 40: fabriq.v1.Fabriq.GetMany:output_type -> fabriq.v1.RowReply
	10, // 41: fabriq.v1.Fabriq.VectorSimilar:output_type -> fabriq.v1.RowReply
	11, // 42: fabriq.v1.Fabriq.VectorUpsert:output_type -> fabriq.v1.Ack
	11, // 43: fabriq.v1.Fabriq.VectorDelete:output_type -> fabriq.v1.Ack
	10, // 44: fabriq.v1.Fabriq.Search:output_type -> fabriq.v1.RowReply
	10, // 45: fabriq.v1.Fabriq.GraphQuery:output_type -> fabriq.v1.RowReply
	20, // 46: fabriq.v1.Fabriq.Subscribe:output_type -> fabriq.v1.SubFrame
	22, // 47: fabriq.v1.Fabriq.LiveQuery:output_type -> fabriq.v1.LiveFrame
	24, // 48: fabriq.v1.Fabriq.Live:output_type -> fabriq.v1.Frame
	28, // 49: fabriq.v1.Fabriq.PutBlob:output_type -> fabriq.v1.BlobInfoReply
	30, // 50: fabriq.v1.Fabriq.GetBlob:output_type -> fabriq.v1.GetBlobFrame
	28, // 51: fabriq.v1.Fabriq.HeadBlob:output_type -> fabriq.v1.BlobInfoReply
	29, // 52: fabriq.v1.Fabriq.DeleteBlob:output_type -> fabriq.v1.BlobAck
	32, // 53: fabriq.v1.Fabriq.PresignBlob:output_type -> fabriq.v1.BlobPresignReply
	36, // [36:54] is the sub-list for method output_type
	18, // [18:36] is the sub-list for method input_type
	18, // [18:18] is the sub-list for extension type_name
	18, // [18:18] is the sub-list for extension extendee
	0,  // [0:18] is the sub-list for field type_name
}

func init() { file_fabriq_v1_fabriq_proto_init() }
func file_fabriq_v1_fabriq_proto_init() {
	if File_fabriq_v1_fabriq_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_fabriq_v1_fabriq_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*Command); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_fabriq_v1_fabriq_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*Result); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_fabriq_v1_fabriq_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*Error); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_fabriq_v1_fabriq_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*ExecRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_fabriq_v1_fabriq_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*ExecReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_fabriq_v1_fabriq_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*ExecBatchRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_fabriq_v1_fabriq_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*ExecBatchReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_fabriq_v1_fabriq_proto_msgTypes[7].Exporter = func(v any, i int) any {
			switch v := v.(*GetRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_fabriq_v1_fabriq_proto_msgTypes[8].Exporter = func(v any, i int) any {
			switch v := v.(*GetManyRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_fabriq_v1_fabriq_proto_msgTypes[9].Exporter = func(v any, i int) any {
			switch v := v.(*ListRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_fabriq_v1_fabriq_proto_msgTypes[10].Exporter = func(v any, i int) any {
			switch v := v.(*RowReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_fabriq_v1_fabriq_proto_msgTypes[11].Exporter = func(v any, i int) any {
			switch v := v.(*Ack); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_fabriq_v1_fabriq_proto_msgTypes[12].Exporter = func(v any, i int) any {
			switch v := v.(*VectorSimilarRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_fabriq_v1_fabriq_proto_msgTypes[13].Exporter = func(v any, i int) any {
			switch v := v.(*VectorUpsertRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_fabriq_v1_fabriq_proto_msgTypes[14].Exporter = func(v any, i int) any {
			switch v := v.(*VectorDeleteRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_fabriq_v1_fabriq_proto_msgTypes[15].Exporter = func(v any, i int) any {
			switch v := v.(*SearchRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_fabriq_v1_fabriq_proto_msgTypes[16].Exporter = func(v any, i int) any {
			switch v := v.(*GraphQueryRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_fabriq_v1_fabriq_proto_msgTypes[17].Exporter = func(v any, i int) any {
			switch v := v.(*SubscribeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_fabriq_v1_fabriq_proto_msgTypes[18].Exporter = func(v any, i int) any {
			switch v := v.(*SubscribeScope); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_fabriq_v1_fabriq_proto_msgTypes[19].Exporter = func(v any, i int) any {
			switch v := v.(*Delta); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_fabriq_v1_fabriq_proto_msgTypes[20].Exporter = func(v any, i int) any {
			switch v := v.(*SubFrame); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_fabriq_v1_fabriq_proto_msgTypes[21].Exporter = func(v any, i int) any {
			switch v := v.(*LiveQueryRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_fabriq_v1_fabriq_proto_msgTypes[22].Exporter = func(v any, i int) any {
			switch v := v.(*LiveFrame); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_fabriq_v1_fabriq_proto_msgTypes[23].Exporter = func(v any, i int) any {
			switch v := v.(*ClientCommand); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_fabriq_v1_fabriq_proto_msgTypes[24].Exporter = func(v any, i int) any {
			switch v := v.(*Frame); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_fabriq_v1_fabriq_proto_msgTypes[25].Exporter = func(v any, i int) any {
			switch v := v.(*BlobChunk); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_fabriq_v1_fabriq_proto_msgTypes[26].Exporter = func(v any, i int) any {
			switch v := v.(*BlobKey); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_fabriq_v1_fabriq_proto_msgTypes[27].Exporter = func(v any, i int) any {
			switch v := v.(*BlobObjectInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_fabriq_v1_fabriq_proto_msgTypes[28].Exporter = func(v any, i int) any {
			switch v := v.(*BlobInfoReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_fabriq_v1_fabriq_proto_msgTypes[29].Exporter = func(v any, i int) any {
			switch v := v.(*BlobAck); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_fabriq_v1_fabriq_proto_msgTypes[30].Exporter = func(v any, i int) any {
			switch v := v.(*GetBlobFrame); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_fabriq_v1_fabriq_proto_msgTypes[31].Exporter = func(v any, i int) any {
			switch v := v.(*BlobPresign); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_fabriq_v1_fabriq_proto_msgTypes[32].Exporter = func(v any, i int) any {
			switch v := v.(*BlobPresignReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_fabriq_v1_fabriq_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_fabriq_v1_fabriq_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   33,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_fabriq_v1_fabriq_proto_goTypes,
		DependencyIndexes: file_fabriq_v1_fabriq_proto_depIdxs,
		MessageInfos:      file_fabriq_v1_fabriq_proto_msgTypes,
	}.Build()
	File_fabriq_v1_fabriq_proto = out.File
	file_fabriq_v1_fabriq_proto_rawDesc = nil
	file_fabriq_v1_fabriq_proto_goTypes = nil
	file_fabriq_v1_fabriq_proto_depIdxs = nil
}
